<?php
declare(strict_types = 1);

use CRM_DeCipicoSaldap_ExtensionUtil as E;

return [
  'saldap_ldap_host' => [
    'name' => 'saldap_ldap_host',
    'group' => 'de_cipico_saldap',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '',
    'title' => E::ts('LDAP Server URI'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('LDAP server URI, e.g. "ldap://ldap.example.com" or "ldaps://ldap.example.com".'),
    'help_text' => E::ts('The URI of the LDAP server. Use ldap:// for unencrypted, ldaps:// for LDAPS.'),
  ],
  'saldap_ldap_port' => [
    'name' => 'saldap_ldap_port',
    'group' => 'de_cipico_saldap',
    'type' => 'Integer',
    'html_type' => 'text',
    'default' => 389,
    'title' => E::ts('LDAP Port'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('LDAP server port (default: 389, LDAPS: 636).'),
  ],
  'saldap_ldap_bind_dn' => [
    'name' => 'saldap_ldap_bind_dn',
    'group' => 'de_cipico_saldap',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '',
    'title' => E::ts('Bind DN'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Distinguished Name for the service account used to search the directory. Leave empty for anonymous bind.'),
  ],
  'saldap_ldap_bind_password' => [
    'name' => 'saldap_ldap_bind_password',
    'group' => 'de_cipico_saldap',
    'type' => 'String',
    'html_type' => 'password',
    'default' => '',
    'title' => E::ts('Bind Password'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Password for the bind DN service account.'),
  ],
  'saldap_ldap_base_dn' => [
    'name' => 'saldap_ldap_base_dn',
    'group' => 'de_cipico_saldap',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '',
    'title' => E::ts('Base DN'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Base Distinguished Name for user searches, e.g. "dc=example,dc=com".'),
  ],
  'saldap_ldap_user_filter' => [
    'name' => 'saldap_ldap_user_filter',
    'group' => 'de_cipico_saldap',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '(&(objectClass=person)(uid=%s))',
    'title' => E::ts('User Search Filter'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('LDAP filter to locate user entries. Use %s as placeholder for the username.'),
    'help_text' => E::ts('Example: (&(objectClass=person)(uid=%s)) or (&(objectClass=user)(sAMAccountName=%s)) for Active Directory.'),
  ],
  'saldap_ldap_group_dn' => [
    'name' => 'saldap_ldap_group_dn',
    'group' => 'de_cipico_saldap',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '',
    'title' => E::ts('Required Group DN'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('If set, only users whose memberOf attribute contains this DN will be authorized. Leave empty to skip group check.'),
  ],
  'saldap_ldap_tls' => [
    'name' => 'saldap_ldap_tls',
    'group' => 'de_cipico_saldap',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => FALSE,
    'title' => E::ts('Use TLS'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Enable TLS for the LDAP connection (startTLS).'),
  ],
  'saldap_ldap_auto_create_user' => [
    'name' => 'saldap_ldap_auto_create_user',
    'group' => 'de_cipico_saldap',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => TRUE,
    'title' => E::ts('Auto-Create Users'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Automatically create a CiviCRM user and contact when an LDAP user logs in for the first time.'),
  ],
  'saldap_ldap_sync_contact' => [
    'name' => 'saldap_ldap_sync_contact',
    'group' => 'de_cipico_saldap',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => TRUE,
    'title' => E::ts('Sync Contact on Every Login'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Update contact name and email from LDAP on every login. Disable to only sync on initial creation.'),
  ],
  'saldap_ldap_attr_mail' => [
    'name' => 'saldap_ldap_attr_mail',
    'group' => 'de_cipico_saldap',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'mail',
    'title' => E::ts('Mail Attribute'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('LDAP attribute containing the email address.'),
  ],
  'saldap_ldap_attr_first_name' => [
    'name' => 'saldap_ldap_attr_first_name',
    'group' => 'de_cipico_saldap',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'givenName',
    'title' => E::ts('First Name Attribute'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('LDAP attribute containing the first/given name.'),
  ],
  'saldap_ldap_attr_last_name' => [
    'name' => 'saldap_ldap_attr_last_name',
    'group' => 'de_cipico_saldap',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'sn',
    'title' => E::ts('Last Name Attribute'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('LDAP attribute containing the last name/surname.'),
  ],
  'saldap_ldap_role_mappings' => [
    'name' => 'saldap_ldap_role_mappings',
    'group' => 'de_cipico_saldap',
    'type' => 'String',
    'html_type' => 'textarea',
    'html_attributes' => [
      'rows' => 3,
      'cols' => 80,
      'class' => 'huge',
    ],
    'default' => '',
    'title' => E::ts('LDAP Group → Role Mappings'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Define which LDAP groups map to which CiviCRM roles.'),
  ],
];
